### ISSUE TITLE
A11y scanning integration for Challenge_gov repo: axe

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1405]
As a site engineer, in order to ensure the quality and accessibility of our code, I would like an automated accessibility tool to test all our of code.

Acceptance criteria:

- [x] [axe-core-rspec](https://github.com/dequelabs/axe-core-gems/tree/develop/packages/axe-core-rspec) is implemented for  Challenge_gov repo and can be turned on to auto-run with the other CI tests at a later time (@jairoanaya  update the library link to an appropriate library)
- [x] A one time manual report is shared with the team

**Comment by TCKapGrp** [comment]
Do we want to change this to AXE based on Kenny's research?

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please share a link to the report in this issue as well.

**Comment by TCKapGrp** [comment]
@jairoanaya , is the AC done for this?  If yes, can you please confirm by checking it off?

**Comment by jairoanaya** [comment]
Here is the link for the report: https://drive.google.com/drive/folders/1yvUtQe-SRVJc-p1n1nMzS6fuykZUISit

**Comment by jairoanaya** [comment]
Summary of work: 

1. Planning strategy to implement Axe Core on Elixir & Phoenix.
2. Investigating the best solution due to nonstandard solutions available.
3. Improving the current Elixir code to test the role use cases, setting testing URLs on a separate file, getting the URL via scripting, and gathering feedback from the team after initial results. 
4. Validation with the team Q&A- Google Docs https://docs.google.com/document/d/1O4EINVUd4epUjNC7-Eyfb_ckDev92f2K42s5Nat9540/edit?usp=drive_link
5. Analyzing Circle CI and integrating accessibility automatic tests on the pipeline. 
6. Adding feedback from the team. 
7. Checking with the development team about automatic current tests and integrating accessibility tests- insights and courses of action were gathered.
8. Enable use case testing parameterization for different roles.
9. Feedback from the team about accessibility - scope was reduced to a one-time report.
10. Populating DB with Active Solver role. 
11. Updating script to generate CSV files.
12. Deployment of code for archiving and future references.

You can explore the final results and further instructions here: [https://drive.google.com/drive/folders/1tgd7XcmPahSz3iSQl0M4-xQjrthVRwFP?usp=drive_link](https://drive.google.com/drive/folders/1tgd7XcmPahSz3iSQl0M4-xQjrthVRwFP?usp=drive_link)

**Comment by mhotch24** [comment]
Completed review and recommendations. Documented here: https://docs.google.com/document/d/1qnHoMIqbpJUuN0GwWystUEfhvsnbFgPPE6e4Pn2GKV0/edit#heading=h.818yzyhrixz9
