### ISSUE TITLE
SPIKE: SRI Scripts

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1480]
- [x] Investigate the implementation of automatic SRI scripts.
- [x] Provide implementation details

**Comment by jairoanaya** [comment]
@r-bartlett-gsa please review the following:

User Story Description:

As a site administrator, I want my Jekyll site to generate and include Subresource Integrity (SRI) automatically hashes for the listed resources below so that my website ensures the integrity and security of loaded assets without requiring manual updates.

**Acceptance Criteria**

1. SRI Hash Generation:

- During the build process, the system should calculate sha384 SRI hashes for the following files:
- /js/public.js
- /client.js
- /css/public.css

2. Hash Injection:

- The generated SRI hashes should automatically be added to the integrity attributes in all relevant script and link tags in the output HTML files.

3. Cross-Browser Compatibility:

- Ensure the injected SRI attributes are compatible with major browsers (e.g., Chrome, Firefox, Safari, Edge).

4. Automation:
-The process should run automatically when executing the Jekyll build command or as part of a CI/CD pipeline.

5. Error Handling:
- If an asset cannot be processed (e.g., missing file, unsupported type), the system should log a warning without interrupting the build process.
- 
6. JS Interdependency:
- The Bundle JS from challenge platform is used on challenge.gov, creating a potential risk of service interruption due to unhandled changes on challenge platform. Therefore, a versioning mechanism must be implemented on challenge platform to control this potential situation effectively on challege.gov deployments. 

**Implementation Tasks**

1. Plugin Development:
- Develop a custom Jekyll plugin (_plugins/auto_sri.rb) to:
- Compute the sha384 hash of asset files.
- Store hashes in site.data.sri. or similar variables.
- Allow hash injection during the build process.

2. Layout Modification:
- Update relevant layout files (e.g., _layouts/footer.html) to use the integrity attribute dynamically using Liquid.

3. Documentation:
- Add documentation for maintaining and extending the SRI hashing functionality.

4. Post-Build Script (Optional):
- If required, create a Ruby post-build script to retroactively add SRI hashes to output files.

**Comment by r-bartlett-gsa** [comment]
New user story created: https://github.com/GSA/Challenge_gov/issues/1488
Update 12/18/24: These updates will not be implemented.
